version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8085:8085"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/fistedarDB
      - SPRING_DATASOURCE_USERNAME=fistedar
      - SPRING_DATASOURCE_PASSWORD=89063263922Abc
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=fistedarDB
      - POSTGRES_USER=fistedar
      - POSTGRES_PASSWORD=89063263922Abc
    ports:
      - "5432:5432"
